/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DespreRouteImport } from './routes/despre'
import { Route as PoliticaCookiesRouteImport } from './routes/politica-cookies'
import { Route as RascumparareRouteImport } from './routes/rascumparare'
import { Route as VehiculeRouteImport } from './routes/vehicule'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as VehiculeIndexRouteImport } from './routes/vehicule.index'
import { Route as VehiculeSlugRouteImport } from './routes/vehicule.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DespreRoute = DespreRouteImport.update({
  id: '/despre',
  path: '/despre',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaCookiesRoute = PoliticaCookiesRouteImport.update({
  id: '/politica-cookies',
  path: '/politica-cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const RascumparareRoute = RascumparareRouteImport.update({
  id: '/rascumparare',
  path: '/rascumparare',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiculeRoute = VehiculeRouteImport.update({
  id: '/vehicule',
  path: '/vehicule',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const VehiculeIndexRoute = VehiculeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VehiculeRoute,
} as any)
const VehiculeSlugRoute = VehiculeSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => VehiculeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/despre': typeof DespreRoute
  '/politica-cookies': typeof PoliticaCookiesRoute
  '/rascumparare': typeof RascumparareRoute
  '/vehicule': typeof VehiculeRouteWithChildren
  '/vehicule/$slug': typeof VehiculeSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/vehicule/': typeof VehiculeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/despre': typeof DespreRoute
  '/politica-cookies': typeof PoliticaCookiesRoute
  '/rascumparare': typeof RascumparareRoute
  '/vehicule/$slug': typeof VehiculeSlugRoute
  '/admin': typeof AdminIndexRoute
  '/vehicule': typeof VehiculeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/despre': typeof DespreRoute
  '/politica-cookies': typeof PoliticaCookiesRoute
  '/rascumparare': typeof RascumparareRoute
  '/vehicule': typeof VehiculeRouteWithChildren
  '/vehicule/$slug': typeof VehiculeSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/vehicule/': typeof VehiculeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/despre'
    | '/politica-cookies'
    | '/rascumparare'
    | '/vehicule'
    | '/vehicule/$slug'
    | '/admin/'
    | '/vehicule/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contact'
    | '/despre'
    | '/politica-cookies'
    | '/rascumparare'
    | '/vehicule/$slug'
    | '/admin'
    | '/vehicule'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/despre'
    | '/politica-cookies'
    | '/rascumparare'
    | '/vehicule'
    | '/vehicule/$slug'
    | '/admin/'
    | '/vehicule/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DespreRoute: typeof DespreRoute
  PoliticaCookiesRoute: typeof PoliticaCookiesRoute
  RascumparareRoute: typeof RascumparareRoute
  VehiculeRoute: typeof VehiculeRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/despre': {
      id: '/despre'
      path: '/despre'
      fullPath: '/despre'
      preLoaderRoute: typeof DespreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-cookies': {
      id: '/politica-cookies'
      path: '/politica-cookies'
      fullPath: '/politica-cookies'
      preLoaderRoute: typeof PoliticaCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rascumparare': {
      id: '/rascumparare'
      path: '/rascumparare'
      fullPath: '/rascumparare'
      preLoaderRoute: typeof RascumparareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicule': {
      id: '/vehicule'
      path: '/vehicule'
      fullPath: '/vehicule'
      preLoaderRoute: typeof VehiculeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/vehicule/': {
      id: '/vehicule/'
      path: '/'
      fullPath: '/vehicule/'
      preLoaderRoute: typeof VehiculeIndexRouteImport
      parentRoute: typeof VehiculeRoute
    }
    '/vehicule/$slug': {
      id: '/vehicule/$slug'
      path: '/$slug'
      fullPath: '/vehicule/$slug'
      preLoaderRoute: typeof VehiculeSlugRouteImport
      parentRoute: typeof VehiculeRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface VehiculeRouteChildren {
  VehiculeSlugRoute: typeof VehiculeSlugRoute
  VehiculeIndexRoute: typeof VehiculeIndexRoute
}

const VehiculeRouteChildren: VehiculeRouteChildren = {
  VehiculeSlugRoute: VehiculeSlugRoute,
  VehiculeIndexRoute: VehiculeIndexRoute,
}

const VehiculeRouteWithChildren = VehiculeRoute._addFileChildren(
  VehiculeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DespreRoute: DespreRoute,
  PoliticaCookiesRoute: PoliticaCookiesRoute,
  RascumparareRoute: RascumparareRoute,
  VehiculeRoute: VehiculeRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
